name: gaussian_flow_impl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - pytorch=2.2.0
  - torchaudio=0.17.0
  - torchvision=2.2.0
  - cudatoolkit=11.8
  - plyfile
  - python=3.9
  - tqdm
  - tensorboard
  - scipy
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
